#DELETE http://localhost:5001/api/helloworld/71f79016-d6e9-41a3-9f44-02b43c5fdd0b
#Accept: application/json

###
POST http://localhost:5001/api/helloworld
Content-Type: application/json

{
  "name": "hello_world"
}

###
PUT http://localhost:5001/api/helloworld/c7cfeae3-8346-4d83-b651-d92b7986ead1
Content-Type: application/json

{
  "name": "hello_world122"
}



