POST http://localhost:5001/api/password_auth/register
Content-Type: application/json


{
  "username": "Guilheim Chataing",
  "password": "test"
}

###
POST http://localhost:5001/api/password_auth/login
Content-Type: application/json


{
  "username": "Guilheim Chataing",
  "password": "test"
}

