POST http://localhost:5001/api/register
Content-Type: application/json


{
  "username": "Guilheim Chataing",
  "password": "test"
}

###
POST http://localhost:5001/api/login
Content-Type: application/json


{
  "username": "Guilheim Chataing",
  "password": "test"
}

