POST http://localhost:5001/api/phone_auth/register
Content-Type: application/json


{
  "username": "Guilheim Chataing",
  "phone": "+33769352015"
}



###

POST http://localhost:5001/api/phone_auth/send_sms
Content-Type: application/json


{
  "phone": "+33769352015"
}



###

POST http://localhost:5001/api/phone_auth/login
Content-Type: application/json

{
  "phone": "+33769352015",
  "code": "730167"
}
